spring: #TODO set it according to your data. it is only template now!
  datasource:
    url: jdbc:postgresql://localhost:5433/auth-db
    username: auth-admin
    password: auth-admin
    driver-class-name: org.postgresql.Driver
  server:
    port: 8080
  sql:
    init:
      mode: always


security:
  jwt:
    secret-key: "mysupersecretkeywithnormallengthstartingfrom32"